/**
 * TaskFlow Engineering Delivery Intelligence Platform
 * Phase 1 Isolated Preview Dataset
 * Clearly marked: "Preview Workspace · Local Sample Data"
 */

export const PREVIEW_META = {
  isSampleData: true,
  badgeLabel: "Preview Workspace · Local Sample Data",
  environment: "Engineering Delivery Intelligence · Phase 1 Preview",
  currentUser: {
    name: "Rakesh Rajput",
    greetingName: "Rakesh",
    role: "Lead Systems Engineer",
    initials: "RR",
    avatarColor: "#8b5cf6",
  },
};

export const PREVIEW_PROJECTS = [
  {
    id: "proj-1",
    name: "Core Engine v3.2",
    code: "COR",
    color: "#8b5cf6",
    status: "At Risk",
    statusType: "warning",
    progress: 72,
    tasksTotal: 14,
    tasksCompleted: 10,
    blockedCount: 1,
    activeBlockers: ["Redis Failover Configuration"],
    deadline: "Oct 15 (Target Release)",
    lead: "Rakesh Rajput",
  },
  {
    id: "proj-2",
    name: "Billing & Subscriptions",
    code: "BIL",
    color: "#ec4899",
    status: "On Track",
    statusType: "positive",
    progress: 88,
    tasksTotal: 8,
    tasksCompleted: 7,
    blockedCount: 0,
    activeBlockers: [],
    deadline: "Sep 30",
    lead: "Marcus Vance",
  },
  {
    id: "proj-3",
    name: "Platform Infrastructure",
    code: "INF",
    color: "#3b82f6",
    status: "Optimal",
    statusType: "positive",
    progress: 92,
    tasksTotal: 12,
    tasksCompleted: 11,
    blockedCount: 0,
    activeBlockers: [],
    deadline: "Nov 01",
    lead: "Alex Rivera",
  },
];

export const PREVIEW_RELEASES = [
  {
    id: "rel-1",
    name: "v3.2.0-GA Core Gateway",
    version: "3.2.0-GA",
    project: "Core Engine v3.2",
    projectColor: "#8b5cf6",
    targetDate: "2026-10-15",
    targetLabel: "Oct 15 (33 days)",
    readinessScore: 68,
    readinessStatus: "At Risk",
    readinessType: "warning",
    milestoneCount: 3,
    milestonesComplete: 1,
    blockedTaskCount: 1,
    projectedDelayDays: 4,
    criticalPathRisk: "1 upstream blocker delaying M2 Session Store QA",
    description: "Major architectural release introducing distributed session storage and low-latency API gateway routing.",
  },
  {
    id: "rel-2",
    name: "v2.4.1-LTS Security Patch",
    version: "2.4.1-LTS",
    project: "Billing & Subscriptions",
    projectColor: "#ec4899",
    targetDate: "2026-09-30",
    targetLabel: "Sep 30 (18 days)",
    readinessScore: 94,
    readinessStatus: "Optimal",
    readinessType: "positive",
    milestoneCount: 2,
    milestonesComplete: 2,
    blockedTaskCount: 0,
    projectedDelayDays: 0,
    criticalPathRisk: "All verification gates passing in staging canary",
    description: "Security update with hardened TLS cipher suites and patched session invalidation endpoints.",
  },
];

export const PREVIEW_MILESTONES = [
  {
    id: "ms-1",
    title: "M1: Storage Layer & Redis Sentinel",
    project: "Core Engine v3.2",
    release: "v3.2.0-GA",
    dueDate: "Sep 22",
    status: "at-risk",
    statusLabel: "At Risk",
    taskCount: 4,
    completedTasks: 3,
  },
  {
    id: "ms-2",
    title: "M2: Session Store & API Benchmarks",
    project: "Core Engine v3.2",
    release: "v3.2.0-GA",
    dueDate: "Oct 02",
    status: "blocked",
    statusLabel: "Blocked (Upstream)",
    taskCount: 3,
    completedTasks: 0,
  },
  {
    id: "ms-3",
    title: "M3: Auth Patch & Token Rotation",
    project: "Billing & Subscriptions",
    release: "v2.4.1-LTS",
    dueDate: "Sep 28",
    status: "completed",
    statusLabel: "Complete",
    taskCount: 3,
    completedTasks: 3,
  },
];

export const PREVIEW_TASKS = [
  {
    id: "tsk-101",
    title: "Redis Failover Configuration",
    project: "Core Engine v3.2",
    projectColor: "#8b5cf6",
    status: "In Progress",
    priority: "high",
    assignedTo: { name: "Marcus Vance", initials: "MV" },
    dueDate: "2026-09-16",
    dueLabel: "Due in 4d",
    isBlocked: true,
    blockedReason: "Waiting on SecOps firewall rule approval for Redis Sentinel port 26379 across cluster subnets.",
    milestone: "M1: Storage Layer & Redis Sentinel",
    release: "v3.2.0-GA Core Gateway",
    dependencies: [],
    downstreamCount: 2,
    downstreamTasks: ["Session Store Benchmarking", "VPC Peering Latency Verification"],
    projectedDelayDays: 4,
    recommendedAction: "Escalate firewall request with SecOps lead on Slack #infra-sec; decouple staging runbook.",
    description: "Set up high-availability sentinel cluster with automatic master failover election.",
  },
  {
    id: "tsk-102",
    title: "Session Store Benchmarking",
    project: "Core Engine v3.2",
    projectColor: "#8b5cf6",
    status: "To Do",
    priority: "high",
    assignedTo: { name: "Sarah Jenkins", initials: "SJ" },
    dueDate: "2026-09-24",
    dueLabel: "Due Sep 24",
    isBlocked: false,
    blockedReason: "",
    milestone: "M2: Session Store & API Benchmarks",
    release: "v3.2.0-GA Core Gateway",
    dependencies: ["Redis Failover Configuration"],
    downstreamCount: 1,
    downstreamTasks: ["VPC Peering Latency Verification"],
    projectedDelayDays: 4,
    recommendedAction: "Blocked by upstream task: Wait for Redis Failover configuration before load tests.",
    description: "Benchmark write throughput under simulated 15,000 concurrent websocket connections.",
  },
  {
    id: "tsk-103",
    title: "VPC Peering Latency Verification",
    project: "Core Engine v3.2",
    projectColor: "#8b5cf6",
    status: "To Do",
    priority: "medium",
    assignedTo: { name: "Alex Rivera", initials: "AR" },
    dueDate: "2026-09-28",
    dueLabel: "Due Sep 28",
    isBlocked: false,
    blockedReason: "",
    milestone: "M2: Session Store & API Benchmarks",
    release: "v3.2.0-GA Core Gateway",
    dependencies: ["Session Store Benchmarking"],
    downstreamCount: 0,
    downstreamTasks: [],
    projectedDelayDays: 4,
    recommendedAction: "Prepare cross-region synthetic ping test suite while waiting on upstream benchmark.",
    description: "Measure p99 network latency across VPC peering routes between us-east-1 and us-east-2.",
  },
  {
    id: "tsk-104",
    title: "Auth Token Rotation Background Sync",
    project: "Core Engine v3.2",
    projectColor: "#8b5cf6",
    status: "In Progress",
    priority: "critical",
    assignedTo: { name: "Rakesh Rajput", initials: "RR" },
    dueDate: "2026-09-10",
    dueLabel: "Overdue by 2 days",
    isBlocked: false,
    blockedReason: "",
    milestone: "M1: Storage Layer & Redis Sentinel",
    release: "v3.2.0-GA Core Gateway",
    dependencies: [],
    downstreamCount: 0,
    downstreamTasks: [],
    projectedDelayDays: 2,
    recommendedAction: "Immediate code review: Background sync worker dropping refresh tokens on desktop reconnect.",
    description: "Ensure silent token renewal does not trigger duplicate session termination during network jitter.",
  },
  {
    id: "tsk-105",
    title: "Database Sharding Fallback Strategy Document",
    project: "Platform Infrastructure",
    projectColor: "#3b82f6",
    status: "To Do",
    priority: "critical",
    assignedTo: null,
    dueDate: "2026-09-18",
    dueLabel: "Due in 6d",
    isBlocked: false,
    blockedReason: "",
    milestone: null,
    release: null,
    dependencies: [],
    downstreamCount: 0,
    downstreamTasks: [],
    projectedDelayDays: 0,
    recommendedAction: "Unassigned critical item: Assign senior platform engineer to author sharding fallback runbook.",
    description: "Architect disaster recovery plan for secondary shard re-indexing under write load.",
  },
  {
    id: "tsk-106",
    title: "Stripe Webhook Idempotency Validation",
    project: "Billing & Subscriptions",
    projectColor: "#ec4899",
    status: "In Progress",
    priority: "high",
    assignedTo: { name: "Marcus Vance", initials: "MV" },
    dueDate: "2026-09-20",
    dueLabel: "Due in 8d",
    isBlocked: false,
    blockedReason: "",
    milestone: "M3: Auth Patch & Token Rotation",
    release: "v2.4.1-LTS Security Patch",
    dependencies: [],
    downstreamCount: 0,
    downstreamTasks: [],
    projectedDelayDays: 0,
    isStale: true,
    staleDays: 5,
    recommendedAction: "Stale in-progress: No commit or status update in 5 days. Verify if blocked on sandbox API.",
    description: "Prevent duplicate invoice events by implementing deduplication store with 24h TTL.",
  },
  {
    id: "tsk-107",
    title: "Validate OAuth2 PKCE Grant Flow",
    project: "Billing & Subscriptions",
    projectColor: "#ec4899",
    status: "In Progress",
    priority: "high",
    assignedTo: { name: "Rakesh Rajput", initials: "RR" },
    dueDate: "2026-09-14",
    dueLabel: "Due in 2d",
    isBlocked: false,
    blockedReason: "",
    milestone: "M3: Auth Patch & Token Rotation",
    release: "v2.4.1-LTS Security Patch",
    dependencies: [],
    downstreamCount: 0,
    downstreamTasks: [],
    projectedDelayDays: 0,
    recommendedAction: "Run automated integration test suite against staging OAuth endpoint.",
    description: "Enforce Proof Key for Code Exchange (PKCE) for all mobile and single-page clients.",
  },
  {
    id: "tsk-108",
    title: "Optimize Compound Index on Task Collections",
    project: "Platform Infrastructure",
    projectColor: "#3b82f6",
    status: "In Progress",
    priority: "medium",
    assignedTo: { name: "Elena Torres", initials: "ET" },
    dueDate: "2026-09-22",
    dueLabel: "Due in 10d",
    isBlocked: false,
    blockedReason: "",
    milestone: null,
    release: null,
    dependencies: [],
    downstreamCount: 0,
    downstreamTasks: [],
    projectedDelayDays: 0,
    recommendedAction: "Verify query execution plan with explain('executionStats') on MongoDB staging replica.",
    description: "Add compound index on { project: 1, status: 1, dueDate: 1 } to eliminate in-memory sort.",
  },
  {
    id: "tsk-109",
    title: "Enforce Project Access RBAC Middleware",
    project: "Core Engine v3.2",
    projectColor: "#8b5cf6",
    status: "To Do",
    priority: "high",
    assignedTo: { name: "Sarah Jenkins", initials: "SJ" },
    dueDate: "2026-09-26",
    dueLabel: "Due in 14d",
    isBlocked: false,
    blockedReason: "",
    milestone: "M1: Storage Layer & Redis Sentinel",
    release: "v3.2.0-GA Core Gateway",
    dependencies: [],
    downstreamCount: 0,
    downstreamTasks: [],
    projectedDelayDays: 0,
    recommendedAction: "Draft unit tests verifying 403 response for non-member task access.",
    description: "Ensure object-level permissions reject unauthorized tenant lookups across all API endpoints.",
  },
  {
    id: "tsk-110",
    title: "Update OpenAPI Contract Spec v3.2",
    project: "Platform Infrastructure",
    projectColor: "#3b82f6",
    status: "To Do",
    priority: "low",
    assignedTo: { name: "Alex Rivera", initials: "AR" },
    dueDate: "2026-10-05",
    dueLabel: "Due in 23d",
    isBlocked: false,
    blockedReason: "",
    milestone: null,
    release: "v3.2.0-GA Core Gateway",
    dependencies: [],
    downstreamCount: 0,
    downstreamTasks: [],
    projectedDelayDays: 0,
    recommendedAction: "Generate Swagger JSON artifacts from route annotations.",
    description: "Document new health and metrics payload schemas for developer portal.",
  },
  {
    id: "tsk-111",
    title: "Rate Limiting Bucket Migration",
    project: "Core Engine v3.2",
    projectColor: "#8b5cf6",
    status: "Done",
    priority: "high",
    assignedTo: { name: "Rakesh Rajput", initials: "RR" },
    dueDate: "2026-09-08",
    dueLabel: "Completed",
    isBlocked: false,
    blockedReason: "",
    milestone: "M1: Storage Layer & Redis Sentinel",
    release: "v3.2.0-GA Core Gateway",
    dependencies: [],
    downstreamCount: 0,
    downstreamTasks: [],
    projectedDelayDays: 0,
    recommendedAction: "Verified in production canary under 10k req/sec load.",
    description: "Migrated token-bucket rate limiter to memory-efficient Valkey 8.0 sorted sets.",
  },
  {
    id: "tsk-112",
    title: "TLS 1.3 Cipher Suite Hardening",
    project: "Platform Infrastructure",
    projectColor: "#3b82f6",
    status: "Done",
    priority: "medium",
    assignedTo: { name: "Elena Torres", initials: "ET" },
    dueDate: "2026-09-06",
    dueLabel: "Completed",
    isBlocked: false,
    blockedReason: "",
    milestone: "M3: Auth Patch & Token Rotation",
    release: "v2.4.1-LTS Security Patch",
    dependencies: [],
    downstreamCount: 0,
    downstreamTasks: [],
    projectedDelayDays: 0,
    recommendedAction: "Passed Qualys SSL Labs A+ rating audit.",
    description: "Disabled legacy CBC ciphers on reverse proxy ingress gateways.",
  },
];

export const PREVIEW_ATTENTION_QUEUE = [
  {
    id: "att-1",
    type: "blocked_upstream",
    severity: "critical",
    severityLabel: "Critical Blocker",
    title: "Redis Failover Configuration",
    project: "Core Engine v3.2",
    projectColor: "#8b5cf6",
    reason: "Blocking 2 downstream tasks · +4 days projected slippage",
    impactMetric: "+4d Delay",
    impactDetail: "Delays 'Session Store Benchmarking' and 'VPC Peering Latency Verification'",
    targetMilestone: "M2: Session Store & API Benchmarks",
    targetRelease: "v3.2.0-GA Core Gateway",
    owner: { name: "Marcus Vance", initials: "MV" },
    dueLabel: "Due in 4d",
    primaryActionLabel: "Inspect Impact",
    actionType: "inspect_dependency",
    rootCause: "Waiting on SecOps firewall rule approval for Redis Sentinel port 26379.",
    recommendedAction: "Escalate firewall request on #infra-sec or decouple staging runbook.",
  },
  {
    id: "att-2",
    type: "overdue_critical",
    severity: "critical",
    severityLabel: "Overdue Critical",
    title: "Auth Token Rotation Background Sync",
    project: "Core Engine v3.2",
    projectColor: "#8b5cf6",
    reason: "Overdue by 2 days · Core Engine",
    impactMetric: "2d Overdue",
    impactDetail: "Affects silent token renewal; potential session drops for desktop clients",
    targetMilestone: "M1: Storage Layer & Redis Sentinel",
    targetRelease: "v3.2.0-GA Core Gateway",
    owner: { name: "Rakesh Rajput", initials: "RR" },
    dueLabel: "Overdue (Sep 10)",
    primaryActionLabel: "Inspect Impact",
    actionType: "inspect_task",
    rootCause: "Token refresh worker encounters race condition during desktop sleep/wake cycle.",
    recommendedAction: "Review token refresh mutex lock before pushing staging release.",
  },
  {
    id: "att-3",
    type: "release_risk",
    severity: "high",
    severityLabel: "Release At Risk",
    title: "v3.2.0-GA Core Gateway Release",
    project: "Core Engine v3.2",
    projectColor: "#8b5cf6",
    reason: "Readiness score at 68% · 1 critical blocker on release path",
    impactMetric: "68% Readiness",
    impactDetail: "Milestone M2 delayed by 4 days due to Redis Sentinel configuration block",
    targetMilestone: "M2: Session Store & API Benchmarks",
    targetRelease: "v3.2.0-GA Core Gateway",
    owner: { name: "Rakesh Rajput", initials: "RR" },
    dueLabel: "Target: Oct 15",
    primaryActionLabel: "Review Release",
    actionType: "inspect_release",
    rootCause: "Critical path obstructed by external SecOps dependency on port 26379.",
    recommendedAction: "Review Decision Record DR-014 to decouple staging benchmarking.",
  },
  {
    id: "att-4",
    type: "unassigned_critical",
    severity: "high",
    severityLabel: "Unassigned Critical",
    title: "Database Sharding Fallback Strategy Document",
    project: "Platform Infrastructure",
    projectColor: "#3b82f6",
    reason: "Unassigned critical priority · Platform Infrastructure",
    impactMetric: "No Owner",
    impactDetail: "Disaster recovery documentation required before planned shard re-index next Tuesday",
    targetMilestone: null,
    targetRelease: null,
    owner: { name: "Unassigned", initials: "—" },
    dueLabel: "Due in 6d",
    primaryActionLabel: "Assign Owner",
    actionType: "assign_owner",
    rootCause: "Created during architecture sprint; ownership not allocated.",
    recommendedAction: "Self-assign or assign to Alex Rivera (Platform Ops Lead).",
  },
  {
    id: "att-5",
    type: "stale_in_progress",
    severity: "medium",
    severityLabel: "Stale In-Progress",
    title: "Stripe Webhook Idempotency Validation",
    project: "Billing & Subscriptions",
    projectColor: "#ec4899",
    reason: "No commit or status update in 5 days (Stale)",
    impactMetric: "5d Inactive",
    impactDetail: "In progress without commits since Monday; risk of stalled delivery",
    targetMilestone: "M3: Auth Patch & Token Rotation",
    targetRelease: "v2.4.1-LTS Security Patch",
    owner: { name: "Marcus Vance", initials: "MV" },
    dueLabel: "Due in 8d",
    primaryActionLabel: "Inspect Status",
    actionType: "inspect_task",
    rootCause: "Marcus Vance engaged in support escalation; task awaiting sandbox API credentials.",
    recommendedAction: "Check with assignee if task is secretly blocked by Stripe sandbox access.",
  },
];

export const PREVIEW_DEPENDENCY_SIGNAL = {
  title: "Critical Path Blocker Propagation",
  upstreamTask: {
    id: "tsk-101",
    title: "Redis Failover Configuration",
    status: "Blocked",
    owner: "Marcus Vance",
    project: "Core Engine v3.2",
    blockedReason: "Waiting on SecOps firewall rule approval for port 26379.",
  },
  downstreamTasks: [
    { id: "tsk-102", title: "Session Store Benchmarking", owner: "Sarah Jenkins", status: "To Do" },
    { id: "tsk-103", title: "VPC Peering Latency Verification", owner: "Alex Rivera", status: "To Do" },
  ],
  affectedMilestone: {
    id: "ms-2",
    title: "M2: Session Store & API Benchmarks",
    dueDate: "Oct 02",
    projectedDelay: "+4 days delay",
  },
  impactedRelease: {
    id: "rel-1",
    title: "v3.2.0-GA Core Gateway",
    targetDate: "Oct 15",
    readinessImpact: "Readiness dropped from 86% to 68%",
  },
  summary: "Upstream firewall blocker propagates through 2 downstream tasks, delaying M2 and projecting a 4-day slippage on v3.2.0-GA release.",
};

export const PREVIEW_FLOW_HEALTH = {
  score: 78,
  label: "STABLE",
  badgeColor: "#3b82f6",
  maxScore: 100,
  activeTasks: 10,
  activeProjects: 3,
  activeMembers: 5,
  penalties: [
    {
      type: "OVERDUE_HIGH_CRITICAL",
      label: "Overdue Critical Task",
      points: 8,
      taskCount: 1,
      target: "Auth Token Rotation Background Sync",
      impact: "Direct 2-day delivery slip on Core Engine M1",
    },
    {
      type: "BLOCKED_TASK",
      label: "Active Blocked Task",
      points: 6,
      taskCount: 1,
      target: "Redis Failover Configuration",
      impact: "Propagates +4 days delay to 2 downstream tasks",
    },
    {
      type: "UNASSIGNED_CRITICAL",
      label: "Unassigned Critical Task",
      points: 4,
      taskCount: 1,
      target: "Database Sharding Fallback Strategy",
      impact: "High-priority architecture task without an assigned owner",
    },
    {
      type: "STALE_IN_PROGRESS",
      label: "Stale In-Progress Task",
      points: 4,
      taskCount: 1,
      target: "Stripe Webhook Idempotency Validation",
      impact: "No code or status activity recorded in 5 days",
    },
  ],
  formula: "Score = 100 - Total Deductions (22 pts deducted). Boundary: ≥90 Optimal, 75–89 Stable, 50–74 At Risk, <50 Critical.",
  thresholds: [
    { label: "Optimal", min: 90, color: "#10b981" },
    { label: "Stable", min: 75, color: "#3b82f6" },
    { label: "At Risk", min: 50, color: "#f59e0b" },
    { label: "Critical", min: 0, color: "#f43f5e" },
  ],
};

export const PREVIEW_TODAY_EXECUTION = [
  {
    id: "tsk-104",
    title: "Auth Token Rotation Background Sync",
    project: "Core Engine v3.2",
    projectColor: "#8b5cf6",
    priority: "critical",
    status: "In Progress",
    dueState: "Overdue (Sep 10)",
    isOverdue: true,
    recommendedAction: "Triage token refresh mutex lock before staging deployment",
    assignee: { name: "Rakesh Rajput", initials: "RR" },
    completed: false,
  },
  {
    id: "tsk-107",
    title: "Validate OAuth2 PKCE Grant Flow",
    project: "Billing & Subscriptions",
    projectColor: "#ec4899",
    priority: "high",
    status: "In Progress",
    dueState: "Due in 2d",
    isOverdue: false,
    recommendedAction: "Execute automated integration test suite against staging endpoint",
    assignee: { name: "Rakesh Rajput", initials: "RR" },
    completed: false,
  },
  {
    id: "tsk-101",
    title: "Redis Failover Configuration",
    project: "Core Engine v3.2",
    projectColor: "#8b5cf6",
    priority: "high",
    status: "In Progress",
    dueState: "Due in 4d",
    isOverdue: false,
    isBlocked: true,
    recommendedAction: "Escalate firewall rule approval on #infra-sec; decouple staging runbook",
    assignee: { name: "Marcus Vance", initials: "MV" },
    completed: false,
  },
  {
    id: "tsk-105",
    title: "Database Sharding Fallback Strategy Document",
    project: "Platform Infrastructure",
    projectColor: "#3b82f6",
    priority: "critical",
    status: "To Do",
    dueState: "Due in 6d",
    isOverdue: false,
    recommendedAction: "Self-assign or assign to Alex Rivera (Platform Ops Lead)",
    assignee: { name: "Unassigned", initials: "—" },
    completed: false,
  },
  {
    id: "tsk-102",
    title: "Session Store Benchmarking",
    project: "Core Engine v3.2",
    projectColor: "#8b5cf6",
    priority: "high",
    status: "To Do",
    dueState: "Due Sep 24",
    isOverdue: false,
    isUpstreamBlocked: true,
    recommendedAction: "Blocked: Wait for Redis Failover configuration before load tests",
    assignee: { name: "Sarah Jenkins", initials: "SJ" },
    completed: false,
  },
];

export const PREVIEW_ACTIVITY = [
  {
    id: "act-1",
    time: "18m ago",
    user: "Marcus Vance",
    action: "flagged as blocked",
    target: "Redis Failover Configuration",
    detail: "Waiting on SecOps firewall rule approval for port 26379",
    type: "blocker",
    icon: "⛔",
  },
  {
    id: "act-2",
    time: "42m ago",
    user: "Sarah Jenkins",
    action: "recorded decision",
    target: "DR-014: Decouple Staging Redis Dependency",
    detail: "Shift Sentinel cluster verification to post-launch patch to unblock M2 benchmarking",
    type: "decision",
    icon: "⚖",
  },
  {
    id: "act-3",
    time: "2h ago",
    user: "Rakesh Rajput",
    action: "completed task",
    target: "Rate Limiting Bucket Migration",
    detail: "Verified in production canary under 10k req/sec load",
    type: "complete",
    icon: "✓",
  },
  {
    id: "act-4",
    time: "3h ago",
    user: "Alex Rivera",
    action: "updated milestone",
    target: "M1: Storage Layer & Redis Sentinel",
    detail: "Status changed from On Track to At Risk due to upstream firewall delay",
    type: "milestone",
    icon: "◈",
  },
  {
    id: "act-5",
    time: "5h ago",
    user: "Elena Torres",
    action: "reassigned owner",
    target: "Auth Token Rotation Background Sync",
    detail: "Reassigned from Unassigned to Rakesh Rajput for rapid triage",
    type: "owner",
    icon: "⇄",
  },
];

export const PREVIEW_DECISION_RECORD = {
  id: "DR-014",
  title: "Decouple Staging Redis Sentinel Dependency",
  author: "Sarah Jenkins (Principal Systems Architect)",
  date: "2026-09-12",
  type: "dependency-decoupled",
  status: "Approved",
  affectedRelease: "v3.2.0-GA Core Gateway",
  affectedMilestone: "M2: Session Store & API Benchmarks",
  affectedTasks: ["Redis Failover Configuration", "Session Store Benchmarking"],
  rationale: "Sentinel cluster configuration is blocked on external SecOps approval for port 26379. To prevent 4-day slippage on v3.2.0-GA, staging load benchmarks will proceed using a standalone Redis 8.0 instance with local failover scripts. Multi-node Sentinel verification will execute as a zero-downtime day-2 operational patch.",
};

export const PREVIEW_SUPPORTING_METRICS = {
  activeWork: 10,
  blockedWork: 1,
  overdueWork: 1,
  unassignedCritical: 1,
  wipPressure: "High (2.1x)",
  wipDetail: "7 tasks in progress across 5 active engineers",
  completedRecent: 2,
};

export const PREVIEW_COMMAND_ITEMS = [
  { id: "cmd-1", label: "Create new task...", category: "Actions", shortcut: "C", icon: "✦" },
  { id: "cmd-2", label: "Create milestone target...", category: "Actions", shortcut: "M", icon: "◈" },
  { id: "cmd-3", label: "Record engineering decision (DR)...", category: "Actions", shortcut: "D", icon: "⚖" },
  { id: "cmd-4", label: "Inspect Redis Sentinel blocker chain", category: "Diagnostics", shortcut: "B", icon: "⛔" },
  { id: "cmd-5", label: "View Flow Health breakdown (78 STABLE)", category: "Diagnostics", shortcut: "H", icon: "⬡" },
  { id: "cmd-6", label: "Jump to Release v3.2.0-GA (At Risk)", category: "Releases", shortcut: "R1", icon: "🚀" },
  { id: "cmd-7", label: "Jump to Release v2.4.1-LTS (Optimal)", category: "Releases", shortcut: "R2", icon: "🚀" },
  { id: "cmd-8", label: "Toggle Navigation Rail", category: "View", shortcut: "[", icon: "☰" },
];
